import { describe, expect, it } from 'vitest'
import {
  hookBaseUrl,
  hookCommand,
  hookScript,
  OURS,
  preCurlMaxTime,
  preHookTimeout
} from './hookScript'

describe('hookScript', () => {
  // Pinned: the script runs on every Bash call of every account with the queue on.
  it('generates the pinned script', () => {
    expect(hookScript(60)).toMatchInlineSnapshot(`
      "#!/bin/sh
      # Generated by ClaudeDeck: test queue hook. It waits for a free test slot and never
      # answers permission prompts. Outside ClaudeDeck tabs it exits at once.
      event=$1
      case $event in
        pre) max=3630 ;;
        post) max=8 ;;
        *) exit 0 ;;
      esac
      token=\${CLAUDEDECK_MCP_TOKEN-}
      url=\${CLAUDEDECK_HOOK_URL-}
      [ \${#token} -eq 64 ] || exit 0
      case $token in *[!0-9a-f]*) exit 0 ;; esac
      case $url in
        http://127.0.0.1:*/*) ;;
        *) exit 0 ;;
      esac
      case $url in *[!A-Za-z0-9:/._-]*) exit 0 ;; esac
      port=\${url#http://127.0.0.1:}
      port=\${port%%/*}
      case $port in ''|*[!0-9]*) exit 0 ;; esac
      input=$(cat) || exit 0
      exec curl -q -s --noproxy '*' --connect-timeout 5 --max-time "$max" \\
        -H 'Content-Type: application/json' --data-binary @- "$url$event" <<EOF
      {"t":"$token","e":"$event","p":$input}
      EOF
      "
    `)
  })

  it('never puts the token on the command line', () => {
    const curl = hookScript(60)
      .split('\n')
      .filter((line) => line.includes('curl'))
      .join('\n')
    expect(curl).not.toContain('token')
  })

  it('derives curl and hook timeouts from the max wait', () => {
    expect(preCurlMaxTime(1)).toBe(90)
    expect(preHookTimeout(1)).toBe(120)
    expect(hookScript(2)).toContain('pre) max=150 ;;')
  })
})

describe('hookCommand', () => {
  it('runs the script with /bin/sh on macOS', () => {
    expect(
      hookCommand(
        '/Users/a/Library/Application Support/ClaudeDeck/accounts/x/claudedeck/test-queue.sh',
        'pre',
        'darwin'
      )
    ).toBe(
      "/bin/sh '/Users/a/Library/Application Support/ClaudeDeck/accounts/x/claudedeck/test-queue.sh' pre"
    )
    expect(hookCommand("/tmp/it's/claudedeck/test-queue.sh", 'post', 'darwin')).toBe(
      "/bin/sh '/tmp/it'\\''s/claudedeck/test-queue.sh' post"
    )
  })

  it('uses forward slashes for Git Bash on Windows', () => {
    const command = hookCommand(
      'C:\\Users\\a\\AppData\\Roaming\\ClaudeDeck\\accounts\\x\\claudedeck\\test-queue.sh',
      'pre',
      'win32'
    )
    expect(command).toBe(
      "/bin/sh 'C:/Users/a/AppData/Roaming/ClaudeDeck/accounts/x/claudedeck/test-queue.sh' pre"
    )
    expect(OURS.test(command)).toBe(true)
  })

  it('builds the hook base URL from the server URL', () => {
    expect(hookBaseUrl('http://127.0.0.1:47821/mcp')).toBe(
      'http://127.0.0.1:47821/hooks/test-queue/'
    )
  })
})
