import { shellQuote } from '../env/shellEnv'
import type { OsName } from '../platform/types'

/** Script file in the account's `claudedeck/` folder. */
export const HOOK_SCRIPT_FILE = 'test-queue.sh'

/** Any hook command pointing at a ClaudeDeck test queue script is ours (any account). */
export const OURS = /claudedeck[\\/]test-queue\.sh/

/** Env var with the tab's hook base URL, set next to the MCP token. */
export const HOOK_URL_ENV = 'CLAUDEDECK_HOOK_URL'

/** Server path prefix of the hook routes; the script appends `pre` or `post`. */
export const HOOK_PATH_PREFIX = '/hooks/test-queue/'

export type HookEvent = 'pre' | 'post'

/** Seconds a post hook (and its curl) may take. */
export const POST_HOOK_TIMEOUT_SECONDS = 10
const POST_CURL_MAX_TIME = 8

/** curl gives up 30 s after the queue's own max wait, the hook 60 s after it. */
export const preCurlMaxTime = (maxWaitMinutes: number): number => maxWaitMinutes * 60 + 30
export const preHookTimeout = (maxWaitMinutes: number): number => maxWaitMinutes * 60 + 60

/** Hook base URL for a running server (`http://127.0.0.1:<port>/hooks/test-queue/`). */
export function hookBaseUrl(serverUrl: string): string {
  const url = new URL(serverUrl)
  return `${url.protocol}//${url.host}${HOOK_PATH_PREFIX}`
}

/**
 * POSIX sh script Claude Code runs for PreToolUse / PostToolUse(Failure) on Bash calls.
 *
 * - Does nothing unless the tab's token and hook URL are well formed, so other `claude`
 *   processes on the same config dir and shell tabs are unaffected.
 * - The token never reaches argv: it travels in the body, fed to curl's stdin by a here-doc.
 *   Expanded values inside a here-doc are not expanded again, so the payload stays inert.
 * - `exec` makes curl the hook process: when Claude kills the hook, the socket closes and the
 *   server sees it. `-q` ignores any .curlrc; `--noproxy` keeps loopback off proxies.
 * - No `--fail`: whatever the server answers (an empty body when it has no decision) is the
 *   hook output. Any failure means empty output, so the tool call proceeds.
 */
export function hookScript(maxWaitMinutes: number): string {
  return [
    '#!/bin/sh',
    '# Generated by ClaudeDeck: test queue hook. It waits for a free test slot and never',
    '# answers permission prompts. Outside ClaudeDeck tabs it exits at once.',
    'event=$1',
    'case $event in',
    `  pre) max=${preCurlMaxTime(maxWaitMinutes)} ;;`,
    `  post) max=${POST_CURL_MAX_TIME} ;;`,
    '  *) exit 0 ;;',
    'esac',
    'token=${CLAUDEDECK_MCP_TOKEN-}',
    `url=\${${HOOK_URL_ENV}-}`,
    '[ ${#token} -eq 64 ] || exit 0',
    'case $token in *[!0-9a-f]*) exit 0 ;; esac',
    'case $url in',
    '  http://127.0.0.1:*/*) ;;',
    '  *) exit 0 ;;',
    'esac',
    'case $url in *[!A-Za-z0-9:/._-]*) exit 0 ;; esac',
    'port=${url#http://127.0.0.1:}',
    'port=${port%%/*}',
    "case $port in ''|*[!0-9]*) exit 0 ;; esac",
    'input=$(cat) || exit 0',
    'exec curl -q -s --noproxy \'*\' --connect-timeout 5 --max-time "$max" \\',
    '  -H \'Content-Type: application/json\' --data-binary @- "$url$event" <<EOF',
    '{"t":"$token","e":"$event","p":$input}',
    'EOF',
    ''
  ].join('\n')
}

/**
 * settings.json `command` for one event: `/bin/sh '<script>' pre`. On Windows Claude Code runs
 * hooks with Git Bash, which reads `C:/...` paths; backslashes are turned into slashes.
 */
export function hookCommand(scriptPath: string, event: HookEvent, os: OsName): string {
  const path = os === 'win32' ? scriptPath.replace(/\\/g, '/') : scriptPath
  return `/bin/sh ${shellQuote(path)} ${event}`
}
