import { describe, expect, it } from 'vitest'
import { hookBaseUrl, hookCommand, hookScript, OURS, preHookTimeout, prePolls } from './hookScript'

describe('hookScript', () => {
  // Pinned: the script runs on every Bash call of every account with the queue on.
  it('generates the pinned script', () => {
    expect(hookScript(60)).toMatchInlineSnapshot(`
      "#!/bin/sh
      # Generated by ClaudeDeck: test queue hook. It waits for a free test slot and never
      # answers permission prompts. Outside ClaudeDeck tabs it exits at once.
      event=$1
      case $event in
        pre) max=30; polls=366 ;;
        post) max=8; polls=1 ;;
        *) exit 0 ;;
      esac
      token=\${CLAUDEDECK_MCP_TOKEN-}
      url=\${CLAUDEDECK_HOOK_URL-}
      [ \${#token} -eq 64 ] || exit 0
      case $token in *[!0-9a-f]*) exit 0 ;; esac
      case $url in
        http://127.0.0.1:*/*) ;;
        *) exit 0 ;;
      esac
      case $url in *[!A-Za-z0-9:/._-]*) exit 0 ;; esac
      port=\${url#http://127.0.0.1:}
      port=\${port%%/*}
      case $port in ''|*[!0-9]*) exit 0 ;; esac
      input=$(cat) || exit 0
      out=$(mktemp 2>/dev/null) || exit 0
      pid=
      stop() {
        [ -z "$pid" ] || kill -TERM "$pid" 2>/dev/null
        rm -f "$out"
        exit 0
      }
      trap stop HUP INT TERM
      answer=
      n=0
      while [ "$n" -lt "$polls" ]; do
        n=$((n + 1))
        : >"$out" || break
        printf '%s' "{\\"t\\":\\"$token\\",\\"e\\":\\"$event\\",\\"p\\":$input}" |
          curl -q -s --noproxy '*' --connect-timeout 5 --max-time "$max" \\
            -H 'Content-Type: application/json' --data-binary @- -o "$out" "$url$event" &
        pid=$!
        wait "$pid"
        pid=
        answer=
        IFS= read -r answer <"$out" || :
        [ "$answer" = claudedeck-wait ] || break
      done
      [ "$answer" = claudedeck-wait ] || cat "$out" 2>/dev/null
      rm -f "$out"
      exit 0
      "
    `)
  })

  it('never puts the token on a command line or into a file', () => {
    const script = hookScript(60)
    const curl = script
      .split('\n')
      .filter((line) => line.includes('curl') || line.includes('-H '))
      .join('\n')
    expect(curl).not.toContain('token')
    // The body goes through the builtin printf into curl's stdin; no here-doc temp file.
    expect(script).not.toContain('<<')
    expect(script).toContain('printf \'%s\' "{\\"t\\":\\"$token\\"')
    expect(script).not.toMatch(/\bexec\b/)
  })

  it('derives the hook timeout and poll count from the max wait', () => {
    expect(preHookTimeout(1)).toBe(120)
    expect(prePolls(1)).toBe(12)
    expect(hookScript(2)).toContain('pre) max=30; polls=18 ;;')
  })

  it('refuses a max wait that is not a whole number in range', () => {
    for (const bad of [0, 241, 1.5, Number.NaN, Infinity]) {
      expect(() => preHookTimeout(bad)).toThrow(RangeError)
      expect(() => hookScript(bad)).toThrow(RangeError)
    }
  })
})

describe('hookCommand', () => {
  it('runs the script with /bin/sh on macOS', () => {
    expect(
      hookCommand(
        '/Users/a/Library/Application Support/ClaudeDeck/accounts/x/claudedeck/test-queue.sh',
        'pre',
        'darwin'
      )
    ).toBe(
      "/bin/sh '/Users/a/Library/Application Support/ClaudeDeck/accounts/x/claudedeck/test-queue.sh' pre"
    )
    expect(hookCommand("/tmp/it's/claudedeck/test-queue.sh", 'post', 'darwin')).toBe(
      "/bin/sh '/tmp/it'\\''s/claudedeck/test-queue.sh' post"
    )
  })

  it('uses forward slashes for Git Bash on Windows', () => {
    const command = hookCommand(
      'C:\\Users\\a\\AppData\\Roaming\\ClaudeDeck\\accounts\\x\\claudedeck\\test-queue.sh',
      'pre',
      'win32'
    )
    expect(command).toBe(
      "/bin/sh 'C:/Users/a/AppData/Roaming/ClaudeDeck/accounts/x/claudedeck/test-queue.sh' pre"
    )
    expect(OURS.test(command)).toBe(true)
  })

  it('builds the hook base URL from the server URL', () => {
    expect(hookBaseUrl('http://127.0.0.1:47821/mcp')).toBe(
      'http://127.0.0.1:47821/hooks/test-queue/'
    )
  })
})
