import { shellQuote } from '../env/shellEnv'
import type { OsName } from '../platform/types'

/** Script file in the account's `claudedeck/` folder. */
export const HOOK_SCRIPT_FILE = 'test-queue.sh'

/** Any hook command pointing at a ClaudeDeck test queue script is ours (any account). */
export const OURS = /claudedeck[\\/]test-queue\.sh/

/** Env var with the tab's hook base URL, set next to the MCP token. */
export const HOOK_URL_ENV = 'CLAUDEDECK_HOOK_URL'

/** Server path prefix of the hook routes; the script appends `pre` or `post`. */
export const HOOK_PATH_PREFIX = '/hooks/test-queue/'

export type HookEvent = 'pre' | 'post'

/** Body of a pre poll answered without a decision: the script polls again. */
export const WAIT_MARKER = 'claudedeck-wait'

/** Seconds a post hook (and its curl) may take. */
export const POST_HOOK_TIMEOUT_SECONDS = 10
const POST_CURL_MAX_TIME = 8
/** One pre poll: the server answers within 20 s (a decision or WAIT_MARKER). */
export const PRE_CURL_MAX_TIME = 30
const MAX_WAIT_RANGE = { min: 1, max: 240 }

function checkMaxWait(maxWaitMinutes: number): number {
  if (
    !Number.isInteger(maxWaitMinutes) ||
    maxWaitMinutes < MAX_WAIT_RANGE.min ||
    maxWaitMinutes > MAX_WAIT_RANGE.max
  ) {
    throw new RangeError(`invalid max wait: ${maxWaitMinutes}`)
  }
  return maxWaitMinutes
}

/** The hook may run 60 s past the queue's own max wait. */
export const preHookTimeout = (maxWaitMinutes: number): number =>
  checkMaxWait(maxWaitMinutes) * 60 + 60

/** Polls a pre hook makes at most: the hook timeout over the shortest useful poll (10 s). */
export const prePolls = (maxWaitMinutes: number): number =>
  Math.ceil(preHookTimeout(maxWaitMinutes) / 10)

/** Hook base URL for a running server (`http://127.0.0.1:<port>/hooks/test-queue/`). */
export function hookBaseUrl(serverUrl: string): string {
  const url = new URL(serverUrl)
  return `${url.protocol}//${url.host}${HOOK_PATH_PREFIX}`
}

/**
 * POSIX sh script Claude Code runs for PreToolUse / PostToolUse(Failure) on Bash calls (macOS
 * /bin/sh, Git Bash on Windows).
 *
 * - Does nothing unless the tab's token and hook URL are well formed, so other `claude`
 *   processes on the same config dir and shell tabs are unaffected.
 * - The token never reaches argv or a file: the builtin `printf` pipes the body into curl's
 *   stdin. `%s` prints the payload as it is (no escapes or expansions are applied to it).
 * - Short polls: each curl is answered within 20 s, with a decision (or an empty body) that
 *   ends the loop, or with WAIT_MARKER, after which the script polls again. A script that stops
 *   polling (killed hook, dead claude) is dropped by the server within 10 s.
 * - curl runs in the background and the script `wait`s for it, so a signal (Esc, the hook
 *   timeout) is handled at once: curl gets SIGTERM, the server sees the connection close.
 * - The exit code is always 0: exit 2 would block the tool call. Any failure means empty
 *   output, so the tool call proceeds. `-q` ignores any .curlrc; `--noproxy` keeps loopback off
 *   proxies. The answer goes to a private temp file (mktemp) that is removed on exit.
 */
export function hookScript(maxWaitMinutes: number): string {
  const polls = prePolls(maxWaitMinutes)
  return [
    '#!/bin/sh',
    '# Generated by ClaudeDeck: test queue hook. It waits for a free test slot and never',
    '# answers permission prompts. Outside ClaudeDeck tabs it exits at once.',
    'event=$1',
    'case $event in',
    `  pre) max=${PRE_CURL_MAX_TIME}; polls=${polls} ;;`,
    `  post) max=${POST_CURL_MAX_TIME}; polls=1 ;;`,
    '  *) exit 0 ;;',
    'esac',
    'token=${CLAUDEDECK_MCP_TOKEN-}',
    `url=\${${HOOK_URL_ENV}-}`,
    '[ ${#token} -eq 64 ] || exit 0',
    'case $token in *[!0-9a-f]*) exit 0 ;; esac',
    'case $url in',
    '  http://127.0.0.1:*/*) ;;',
    '  *) exit 0 ;;',
    'esac',
    'case $url in *[!A-Za-z0-9:/._-]*) exit 0 ;; esac',
    'port=${url#http://127.0.0.1:}',
    'port=${port%%/*}',
    "case $port in ''|*[!0-9]*) exit 0 ;; esac",
    'input=$(cat) || exit 0',
    'out=$(mktemp 2>/dev/null) || exit 0',
    'pid=',
    'stop() {',
    '  [ -z "$pid" ] || kill -TERM "$pid" 2>/dev/null',
    '  rm -f "$out"',
    '  exit 0',
    '}',
    'trap stop HUP INT TERM',
    'answer=',
    'n=0',
    'while [ "$n" -lt "$polls" ]; do',
    '  n=$((n + 1))',
    '  : >"$out" || break',
    '  printf \'%s\' "{\\"t\\":\\"$token\\",\\"e\\":\\"$event\\",\\"p\\":$input}" |',
    '    curl -q -s --noproxy \'*\' --connect-timeout 5 --max-time "$max" \\',
    '      -H \'Content-Type: application/json\' --data-binary @- -o "$out" "$url$event" &',
    '  pid=$!',
    '  wait "$pid"',
    '  pid=',
    '  answer=',
    '  IFS= read -r answer <"$out" || :',
    `  [ "$answer" = ${WAIT_MARKER} ] || break`,
    'done',
    `[ "$answer" = ${WAIT_MARKER} ] || cat "$out" 2>/dev/null`,
    'rm -f "$out"',
    'exit 0',
    ''
  ].join('\n')
}

/**
 * settings.json `command` for one event: `/bin/sh '<script>' pre`. On Windows Claude Code runs
 * hooks with Git Bash, which reads `C:/...` paths; backslashes are turned into slashes.
 */
export function hookCommand(scriptPath: string, event: HookEvent, os: OsName): string {
  const path = os === 'win32' ? scriptPath.replace(/\\/g, '/') : scriptPath
  return `/bin/sh ${shellQuote(path)} ${event}`
}
