import { describe, expect, it } from 'vitest'
import {
  GUARD_UNAVAILABLE_REPLY,
  hookBaseUrl,
  hookCommand,
  hookScript,
  OURS,
  preHookTimeout,
  prePolls
} from './hookScript'

describe('hookScript', () => {
  // Pinned: the script runs on every Bash call of every account with the queue on.
  // Pinned: the script runs on every guarded tool call of every account.
  it('generates the pinned script', () => {
    expect(hookScript({ guard: true, maxWaitMinutes: 60 })).toMatchInlineSnapshot(`
      "#!/bin/sh
      # Generated by ClaudeDeck: command guard and test queue hook. It checks tool calls against
      # the guard rules and waits for a free test slot. Outside ClaudeDeck tabs it exits at once.
      event=$1
      case $event in
        pre|post) ;;
        *) exit 0 ;;
      esac
      guard=1
      polls=366
      token=\${CLAUDEDECK_MCP_TOKEN-}
      url=\${CLAUDEDECK_HOOK_URL-}
      [ \${#token} -eq 64 ] || exit 0
      case $token in *[!0-9a-f]*) exit 0 ;; esac
      case $url in
        http://127.0.0.1:*/*) ;;
        *) exit 0 ;;
      esac
      case $url in *[!A-Za-z0-9:/._-]*) exit 0 ;; esac
      port=\${url#http://127.0.0.1:}
      port=\${port%%/*}
      case $port in ''|*[!0-9]*) exit 0 ;; esac
      deny() {
        [ "$guard" = 1 ] && [ "$event" = pre ] && printf '%s\\n' '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"ClaudeDeck command guard is unavailable, so this tool call was blocked. Ask the user to check that ClaudeDeck is running, then try again."},"systemMessage":"ClaudeDeck command guard is unavailable; the tool call was blocked."}'
      }
      input=$(cat) || { deny; exit 0; }
      out=$(mktemp 2>/dev/null) || { deny; exit 0; }
      code=$(mktemp 2>/dev/null) || { rm -f "$out"; deny; exit 0; }
      pid=
      finish() {
        [ -z "$pid" ] || kill -TERM "$pid" 2>/dev/null
        rm -f "$out" "$code"
        exit 0
      }
      trap finish HUP INT TERM
      # send <body event> <route> <seconds>: the answer in $out, its first line in $answer.
      send() {
        status=
        answer=
        : >"$out" && : >"$code" || return 0
        printf '%s' "{\\"t\\":\\"$token\\",\\"e\\":\\"$1\\",\\"p\\":$input}" |
          curl -q -s --noproxy '*' --connect-timeout 2 --max-time "$3" -w '%{http_code}' \\
            -H 'Content-Type: application/json' --data-binary @- -o "$out" "$url$2" >"$code" &
        pid=$!
        wait "$pid"
        pid=
        IFS= read -r status <"$code" || :
        IFS= read -r answer <"$out" || :
      }
      if [ "$event" = post ]; then
        send post post 8
        finish
      fi
      send guard pre 5
      case $status in
        200) ;;
        401) finish ;;
        *) deny; finish ;;
      esac
      if [ "$answer" != claudedeck-queue ]; then
        cat "$out" 2>/dev/null
        finish
      fi
      n=0
      while [ "$n" -lt "$polls" ]; do
        n=$((n + 1))
        send pre pre 30
        [ "$answer" = claudedeck-wait ] || break
      done
      [ "$answer" = claudedeck-wait ] || [ "$answer" = claudedeck-queue ] || cat "$out" 2>/dev/null
      finish
      "
    `)
  })

  it('fails closed only while the guard is on', () => {
    expect(hookScript({ guard: true, maxWaitMinutes: 60 })).toContain('guard=1')
    expect(hookScript({ guard: false, maxWaitMinutes: 60 })).toContain('guard=0')
    // The reply sits in single quotes in the script.
    expect(GUARD_UNAVAILABLE_REPLY).not.toContain("'")
    expect(JSON.parse(GUARD_UNAVAILABLE_REPLY).hookSpecificOutput.permissionDecision).toBe('deny')
  })

  it('never puts the token on a command line or into a file', () => {
    const script = hookScript({ guard: true, maxWaitMinutes: 60 })
    const curl = script
      .split('\n')
      .filter((line) => line.includes('curl') || line.includes('-H '))
      .join('\n')
    expect(curl).not.toContain('token')
    // The body goes through the builtin printf into curl's stdin; no here-doc temp file.
    expect(script).not.toContain('<<')
    expect(script).toContain('printf \'%s\' "{\\"t\\":\\"$token\\"')
    expect(script).not.toMatch(/\bexec\b/)
  })

  it('derives the hook timeout and poll count from the max wait', () => {
    expect(preHookTimeout(1)).toBe(120)
    expect(prePolls(1)).toBe(12)
    expect(hookScript({ guard: true, maxWaitMinutes: 2 })).toContain('polls=18')
  })

  it('refuses a max wait that is not a whole number in range', () => {
    for (const bad of [0, 241, 1.5, Number.NaN, Infinity]) {
      expect(() => preHookTimeout(bad)).toThrow(RangeError)
      expect(() => hookScript({ guard: true, maxWaitMinutes: bad })).toThrow(RangeError)
    }
  })
})

describe('hookCommand', () => {
  it('runs the script with /bin/sh on macOS', () => {
    expect(
      hookCommand(
        '/Users/a/Library/Application Support/ClaudeDeck/accounts/x/claudedeck/test-queue.sh',
        'pre',
        'darwin'
      )
    ).toBe(
      "/bin/sh '/Users/a/Library/Application Support/ClaudeDeck/accounts/x/claudedeck/test-queue.sh' pre"
    )
    expect(hookCommand("/tmp/it's/claudedeck/test-queue.sh", 'post', 'darwin')).toBe(
      "/bin/sh '/tmp/it'\\''s/claudedeck/test-queue.sh' post"
    )
  })

  it('uses forward slashes for Git Bash on Windows', () => {
    const command = hookCommand(
      'C:\\Users\\a\\AppData\\Roaming\\ClaudeDeck\\accounts\\x\\claudedeck\\test-queue.sh',
      'pre',
      'win32'
    )
    expect(command).toBe(
      "/bin/sh 'C:/Users/a/AppData/Roaming/ClaudeDeck/accounts/x/claudedeck/test-queue.sh' pre"
    )
    expect(OURS.test(command)).toBe(true)
  })

  it('recognises the current and the old script names', () => {
    expect(OURS.test("/bin/sh '/x/claudedeck/hook.sh' pre")).toBe(true)
    expect(OURS.test("/bin/sh '/x/claudedeck/test-queue.sh' post")).toBe(true)
    expect(OURS.test("/bin/sh '/x/other/hook.sh' pre")).toBe(false)
  })

  it('builds the hook base URL from the server URL', () => {
    expect(hookBaseUrl('http://127.0.0.1:47821/mcp')).toBe('http://127.0.0.1:47821/hooks/')
  })
})
