import { describe, expect, it } from 'vitest'
import {
  GUARD_UNAVAILABLE_REPLY,
  guardKeyFile,
  hookBaseUrl,
  hookCommand,
  hookScript,
  OURS,
  preHookTimeout,
  prePolls
} from './hookScript'

describe('hookScript', () => {
  // Pinned: the script runs on every Bash call of every account with the queue on.
  // Pinned: the script runs on every guarded tool call of every account.
  it('generates the pinned script', () => {
    expect(hookScript({ guard: true, maxWaitMinutes: 60 })).toMatchInlineSnapshot(`
      "#!/bin/sh
      # Generated by ClaudeDeck: command guard and test queue hook. It checks tool calls against
      # the guard rules and waits for a free test slot. Outside ClaudeDeck it exits at once.
      event=$1
      case $event in
        pre|post) ;;
        *) exit 0 ;;
      esac
      guard=1
      polls=366
      hex64() {
        [ \${#1} -eq 64 ] || return 1
        case $1 in *[!0-9a-f]*) return 1 ;; esac
      }
      hookurl() {
        case $1 in
          http://127.0.0.1:*/*) ;;
          *) return 1 ;;
        esac
        case $1 in *[!A-Za-z0-9:/._-]*) return 1 ;; esac
        p=\${1#http://127.0.0.1:}
        p=\${p%%/*}
        case $p in ''|*[!0-9]*) return 1 ;; esac
      }
      # The key file next to this script: the key, the hook URL, ClaudeDeck's pid and start time.
      key=
      keyurl=
      kpid=
      kstart=
      case $0 in
        */*) keyfile=\${0%/*}/guard.key ;;
        *\\\\*) keyfile=\${0%\\\\*}/guard.key ;;
        *) keyfile=./guard.key ;;
      esac
      if [ -f "$keyfile" ]; then
        { IFS= read -r key; IFS= read -r keyurl; IFS= read -r kpid; IFS= read -r kstart; } <"$keyfile" 2>/dev/null || :
      fi
      hex64 "$key" || key=
      hookurl "$keyurl" || keyurl=
      case $kpid in ''|*[!0-9]*) kpid= ;; esac
      deny() {
        [ "$guard" = 1 ] && [ "$event" = pre ] && printf '%s\\n' '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"ClaudeDeck command guard is unavailable, so this tool call was blocked. Ask the user to check that ClaudeDeck is running, then try again."},"systemMessage":"ClaudeDeck command guard is unavailable; the tool call was blocked."}'
      }
      token=\${CLAUDEDECK_MCP_TOKEN-}
      url=$keyurl
      route=pre
      if hex64 "$token" && [ -n "$url" ]; then
        mode=tab
      elif [ "$guard" = 1 ] && [ "$event" = pre ] && [ -n "$key" ] && [ -n "$url" ]; then
        mode=key
        token=$key
        route=guard
      elif hex64 "$token"; then
        # A tab without a usable key file: the guard cannot be reached safely.
        cat >/dev/null 2>&1
        deny
        exit 0
      else
        exit 0
      fi
      # ClaudeDeck still runs: its pid is alive and started when the key file says.
      alive() {
        [ -n "$kpid" ] || return 1
        kill -0 "$kpid" 2>/dev/null || return 1
        [ -n "$kstart" ] || return 0
        now=$(LC_ALL=C ps -o lstart= -p "$kpid" 2>/dev/null) || return 0
        set -f
        set -- $now
        set +f
        [ "$*" = "$kstart" ]
      }
      input=$(cat) || { deny; exit 0; }
      out=$(mktemp 2>/dev/null) || { deny; exit 0; }
      code=$(mktemp 2>/dev/null) || { rm -f "$out"; deny; exit 0; }
      pid=
      stage=
      finish() {
        [ -z "$pid" ] || kill -TERM "$pid" 2>/dev/null
        rm -f "$out" "$code"
        # Stopped while the guard was checking: the call is denied, not let through.
        [ "$stage" = guard ] && deny
        exit 0
      }
      trap finish HUP INT TERM
      # send <body event> <route> <seconds>: the answer in $out, its first line in $answer,
      # curl's exit code in $rc and whether it connected at all in $connected.
      send() {
        status=
        answer=
        rc=0
        connected=
        : >"$out" && : >"$code" || return 0
        printf '%s' "{\\"t\\":\\"$token\\",\\"e\\":\\"$1\\",\\"p\\":$input}" |
          curl -q -s --noproxy '*' --connect-timeout 2 --max-time "$3" -w '%{http_code} %{time_connect}' \\
            -H 'Content-Type: application/json' --data-binary @- -o "$out" "$url$2" >"$code" &
        pid=$!
        wait "$pid"
        rc=$?
        pid=
        read -r status connect <"$code" || :
        case $connect in *[1-9]*) connected=1 ;; esac
        IFS= read -r answer <"$out" || :
      }
      if [ "$event" = post ]; then
        [ "$mode" = tab ] && send post post 8
        finish
      fi
      stage=guard
      send guard "$route" 5
      # A tab token the server does not know: the account key, when there is one.
      if [ "$status" = 401 ] && [ "$mode" = tab ] && [ "$guard" = 1 ] && [ -n "$key" ]; then
        mode=key
        token=$key
        route=guard
        send guard "$route" 5
      fi
      # With the key, no connection while ClaudeDeck is gone means it is not running: pass.
      case $mode:$status in
        *:200) ;;
        key:000)
          if { [ "$rc" = 7 ] || [ -z "$connected" ]; } && ! alive; then stage=; finish; fi
          stage=; deny; finish ;;
        *) stage=; deny; finish ;;
      esac
      stage=
      if [ "$mode" = key ] || [ "$answer" != claudedeck-queue ]; then
        cat "$out" 2>/dev/null
        finish
      fi
      n=0
      while [ "$n" -lt "$polls" ]; do
        n=$((n + 1))
        send pre pre 30
        [ "$answer" = claudedeck-wait ] || break
      done
      [ "$answer" = claudedeck-wait ] || [ "$answer" = claudedeck-queue ] || cat "$out" 2>/dev/null
      finish
      "
    `)
  })

  it('fails closed only while the guard is on', () => {
    expect(hookScript({ guard: true, maxWaitMinutes: 60 })).toContain('guard=1')
    expect(hookScript({ guard: false, maxWaitMinutes: 60 })).toContain('guard=0')
    // The reply sits in single quotes in the script.
    expect(GUARD_UNAVAILABLE_REPLY).not.toContain("'")
    expect(JSON.parse(GUARD_UNAVAILABLE_REPLY).hookSpecificOutput.permissionDecision).toBe('deny')
  })

  it('takes the server URL only from the key file, never from the environment', () => {
    const script = hookScript({ guard: true, maxWaitMinutes: 60 })
    expect(script).not.toContain('CLAUDEDECK_HOOK_URL')
    expect(script).toContain('url=$keyurl')
  })

  it('checks that ClaudeDeck is gone before passing a key call, except on Windows', () => {
    const mac = hookScript({ guard: true, maxWaitMinutes: 60, os: 'darwin' })
    expect(mac).toContain('kill -0 "$kpid"')
    expect(mac).toContain('LC_ALL=C ps -o lstart= -p "$kpid"')
    const win = hookScript({ guard: true, maxWaitMinutes: 60, os: 'win32' })
    expect(win).toContain('alive() { return 1; }')
    expect(win).not.toContain('kill -0')
  })

  it('writes the key file with the process identity on its own lines', () => {
    expect(
      guardKeyFile({
        key: 'k',
        url: 'http://127.0.0.1:1/hooks/',
        pid: 7,
        startTime: ' Fri Oct  9 02:53:46 2026 '
      })
    ).toBe('k\nhttp://127.0.0.1:1/hooks/\n7\nFri Oct 9 02:53:46 2026\n')
    expect(guardKeyFile({ key: 'k', url: null })).toBe('k\n\n\n\n')
  })

  it('never puts the token on a command line or into a file', () => {
    const script = hookScript({ guard: true, maxWaitMinutes: 60 })
    const curl = script
      .split('\n')
      .filter((line) => line.includes('curl') || line.includes('-H '))
      .join('\n')
    expect(curl).not.toContain('token')
    // The body goes through the builtin printf into curl's stdin; no here-doc temp file.
    expect(script).not.toContain('<<')
    expect(script).toContain('printf \'%s\' "{\\"t\\":\\"$token\\"')
    expect(script).not.toMatch(/\bexec\b/)
  })

  it('derives the hook timeout and poll count from the max wait', () => {
    expect(preHookTimeout(1)).toBe(120)
    expect(prePolls(1)).toBe(12)
    expect(hookScript({ guard: true, maxWaitMinutes: 2 })).toContain('polls=18')
  })

  it('refuses a max wait that is not a whole number in range', () => {
    for (const bad of [0, 241, 1.5, Number.NaN, Infinity]) {
      expect(() => preHookTimeout(bad)).toThrow(RangeError)
      expect(() => hookScript({ guard: true, maxWaitMinutes: bad })).toThrow(RangeError)
    }
  })
})

describe('hookCommand', () => {
  it('runs the script with /bin/sh on macOS', () => {
    expect(
      hookCommand(
        '/Users/a/Library/Application Support/ClaudeDeck/accounts/x/claudedeck/test-queue.sh',
        'pre',
        'darwin'
      )
    ).toBe(
      "/bin/sh '/Users/a/Library/Application Support/ClaudeDeck/accounts/x/claudedeck/test-queue.sh' pre"
    )
    expect(hookCommand("/tmp/it's/claudedeck/test-queue.sh", 'post', 'darwin')).toBe(
      "/bin/sh '/tmp/it'\\''s/claudedeck/test-queue.sh' post"
    )
  })

  it('uses forward slashes for Git Bash on Windows', () => {
    const command = hookCommand(
      'C:\\Users\\a\\AppData\\Roaming\\ClaudeDeck\\accounts\\x\\claudedeck\\test-queue.sh',
      'pre',
      'win32'
    )
    expect(command).toBe(
      "/bin/sh 'C:/Users/a/AppData/Roaming/ClaudeDeck/accounts/x/claudedeck/test-queue.sh' pre"
    )
    expect(OURS.test(command)).toBe(true)
  })

  it('recognises the current and the old script names', () => {
    expect(OURS.test("/bin/sh '/x/claudedeck/hook.sh' pre")).toBe(true)
    expect(OURS.test("/bin/sh '/x/claudedeck/test-queue.sh' post")).toBe(true)
    expect(OURS.test("/bin/sh '/x/other/hook.sh' pre")).toBe(false)
  })

  it('builds the hook base URL from the server URL', () => {
    expect(hookBaseUrl('http://127.0.0.1:47821/mcp')).toBe('http://127.0.0.1:47821/hooks/')
  })
})
