export const IPC = {
  stateGet: 'state:get',
  accountCreate: 'account:create',
  accountUpdate: 'account:update',
  accountRemove: 'account:remove',
  accountStatus: 'account:status',
  projectCreate: 'project:create',
  projectUpdate: 'project:update',
  projectRemove: 'project:remove',
  sessionCreate: 'session:create',
  sessionRename: 'session:rename',
  sessionRemove: 'session:remove',
  settingsSetLanguage: 'settings:setLanguage',
  ptyStartSession: 'pty:startSession',
  ptyStartLogin: 'pty:startLogin',
  ptyWrite: 'pty:write',
  ptyResize: 'pty:resize',
  ptyKill: 'pty:kill',
  ptyData: 'pty:data',
  ptyExit: 'pty:exit',
  systemPickFolder: 'system:pickFolder',
  systemPathExists: 'system:pathExists',
  systemClaudeAvailable: 'system:claudeAvailable',
  menuOpenSettings: 'menu:openSettings',
  updateCheck: 'update:check',
  updateOpen: 'update:open',
  updateAvailable: 'update:available',
  profileSummarize: 'profile:summarize',
  profileDiff: 'profile:diff',
  profileImport: 'profile:import',
  profileStartOptimize: 'profile:startOptimize',
  profileOpenFolder: 'profile:openFolder',
  profileGuidelinesUpdated: 'profile:guidelinesUpdated',
  profileTakeGuidelineUpdates: 'profile:takeGuidelineUpdates',
  notesList: 'notes:list',
  notesRead: 'notes:read',
  notesWatch: 'notes:watch',
  notesUnwatch: 'notes:unwatch',
  notesChanged: 'notes:changed',
  notesOpen: 'notes:open',
  notesReveal: 'notes:reveal',
  mcpInfo: 'mcp:info',
  stateChanged: 'state:changed',
  sessionOpenRequest: 'session:openRequest',
  optimizeStart: 'optimize:start',
  optimizeGet: 'optimize:get',
  optimizeList: 'optimize:list',
  optimizeAnswer: 'optimize:answer',
  optimizeCancel: 'optimize:cancel',
  optimizeRevert: 'optimize:revert',
  optimizeUpdate: 'optimize:update'
} as const

export type IpcResult<T> = { ok: true; data: T } | { ok: false; code: string }

export const loginPtyId = (accountId: string): string => `login:${accountId}`
export const optimizePtyId = (accountId: string): string => `optimize:${accountId}`
