import { ipcMain, type IpcMainEvent } from 'electron'
import { IPC } from '../../shared/ipc'
import type { IpcTools } from '../ipcUtil'

/** Account ids are generated by the repository; anything else is not an account. */
const ACCOUNT_ID = /^[\w-]{1,64}$/

const isAccountId = (v: unknown): v is string => typeof v === 'string' && ACCOUNT_ID.test(v)

interface Deps {
  handle: IpcTools['handle']
  /** Only the main window knows the selected account; the popover must not change it. */
  isMainSender: (event: IpcMainEvent) => boolean
  setSelectedAccount: (accountId: string | null) => void
  trayAccount: () => string | null
  openMain: () => void
  quit: () => void
  packaged: () => boolean
}

export function registerAppIpc({
  handle,
  isMainSender,
  setSelectedAccount,
  trayAccount,
  openMain,
  quit,
  packaged
}: Deps): void {
  ipcMain.on(IPC.appSelectedAccount, (event, accountId: unknown) => {
    if (!isMainSender(event)) return
    if (accountId === null || isAccountId(accountId)) setSelectedAccount(accountId)
  })
  handle(IPC.appTrayAccount, () => trayAccount())
  handle(IPC.appOpenMain, () => {
    openMain()
    return null
  })
  handle(IPC.appQuit, () => {
    // Replies first; quitting right away would tear down the window that waits for the answer.
    setImmediate(quit)
    return null
  })
  handle(IPC.appPackaged, () => packaged())
}
