import { existsSync } from 'node:fs'
import { shellQuote } from '../env/shellEnv'
import { WIN_DEFAULT_SYSTEM_ROOT, WIN_POWERSHELL } from '../platform/constants'
import type { OsName } from '../platform/types'

/** File the scripts write the statusline JSON to, inside the usage folder. */
export const USAGE_RAW_FILE = 'usage-raw.json'

export const POSIX_SCRIPT_FILE = 'statusline.sh'
export const WINDOWS_SCRIPT_FILE = 'statusline.ps1'
export const SCRIPT_FILES = [POSIX_SCRIPT_FILE, WINDOWS_SCRIPT_FILE]
/** The account's own statusline, chained by the script. */
export const ORIGINAL_FILE = 'statusline-original.json'

/**
 * Files ClaudeDeck owns in the usage folder (`claudedeck/`), as glob names: the scripts run on
 * every prompt, the rest feeds them or the app. Includes the scripts' temp files.
 */
export const APP_MANAGED_USAGE_FILES = [
  ...SCRIPT_FILES,
  ORIGINAL_FILE,
  USAGE_RAW_FILE,
  `${USAGE_RAW_FILE}.*`
]

export const scriptFileName = (os: OsName): string =>
  os === 'win32' ? WINDOWS_SCRIPT_FILE : POSIX_SCRIPT_FILE

// Any command pointing at a ClaudeDeck script is ours, even one copied from another account.
export const OURS = /claudedeck[\\/]statusline\.(sh|ps1)/

// ---- POSIX -----------------------------------------------------------------------------------

/**
 * Script Claude Code runs as the statusline: stores the JSON it receives (only when it carries
 * `rate_limits`) and hands the same input to the user's original statusline, if any.
 */
export function posixStatuslineScript(dir: string, originalCommand: string | null): string {
  const chain = originalCommand
    ? `printf '%s\\n' "$input" | /bin/sh -c ${shellQuote(originalCommand)} 2>/dev/null`
    : ':'
  return [
    '#!/bin/sh',
    '# Generated by ClaudeDeck. Records plan usage, then runs the original statusline.',
    'input=$(cat 2>/dev/null)',
    `dir=${shellQuote(dir)}`,
    'case $input in',
    `  *'"rate_limits"'*)`,
    `    tmp="$dir/${USAGE_RAW_FILE}.$$"`,
    `    { printf '%s' "$input" > "$tmp" && mv -f "$tmp" "$dir/${USAGE_RAW_FILE}"; } 2>/dev/null ||`,
    `      rm -f "$tmp" 2>/dev/null`,
    '    ;;',
    'esac',
    chain,
    'exit 0',
    ''
  ].join('\n')
}

/** settings.json `command` for the POSIX script. */
export const posixStatuslineCommand = (scriptPath: string): string => shellQuote(scriptPath)

// ---- Windows ---------------------------------------------------------------------------------

/** Env var Claude Code reads for the Git Bash location. */
export const GIT_BASH_ENV = 'CLAUDE_CODE_GIT_BASH_PATH'
/** Default Git for Windows install locations, checked after the env var. */
export const GIT_BASH_CANDIDATES = [
  'C:\\Program Files\\Git\\bin\\bash.exe',
  'C:\\Program Files (x86)\\Git\\bin\\bash.exe'
]

/** Shell the Windows script hands the original statusline command to. */
export type ChainShell = { kind: 'bash' | 'powershell'; path: string }

/** A Windows root safe to leave unquoted in a command both Git Bash and PowerShell read. */
const PLAIN_WINDOWS_DIR = /^[a-zA-Z]:[\\/][\w\\/.-]*$/

/**
 * Absolute Windows PowerShell 5.1 path with forward slashes, from `%SystemRoot%` (any case)
 * with `C:/Windows` as fallback. Absolute so neither PATH nor the current folder can stand in
 * for it; a root that would need quoting falls back too.
 */
export function windowsPowerShellPath(env: Record<string, string | undefined>): string {
  const key = Object.keys(env).find((name) => name.toUpperCase() === 'SYSTEMROOT')
  const fromEnv = key ? env[key]?.trim() : undefined
  const root = fromEnv && PLAIN_WINDOWS_DIR.test(fromEnv) ? fromEnv : WIN_DEFAULT_SYSTEM_ROOT
  return [root.replace(/[\\/]+$/, ''), ...WIN_POWERSHELL].join('/').replace(/\\/g, '/')
}

/** Git Bash like Claude Code finds it (env var, then default locations); null when absent. */
export function findGitBash(
  env: Record<string, string | undefined>,
  exists: (path: string) => boolean = existsSync
): string | null {
  const fromEnv = env[GIT_BASH_ENV]?.trim()
  const candidates = fromEnv ? [fromEnv, ...GIT_BASH_CANDIDATES] : GIT_BASH_CANDIDATES
  return candidates.find((path) => exists(path)) ?? null
}

export const chainShellFor = (gitBash: string | null, powershell: string): ChainShell =>
  gitBash ? { kind: 'bash', path: gitBash } : { kind: 'powershell', path: powershell }

/** Every character PowerShell reads as a single quote (ASCII and the typographic ones). */
const PS_SINGLE_QUOTE = /['\u2018\u2019\u201A\u201B]/
/** Every character PowerShell reads as a double quote. */
const PS_DOUBLE_QUOTES = /["\u201C\u201D\u201E]/

/** PowerShell single-quoted literal: any single-quote character is doubled. */
export const psQuote = (value: string): string =>
  `'${value.replace(new RegExp(PS_SINGLE_QUOTE.source, 'g'), (quote) => quote + quote)}'`

/**
 * One argument in Windows command line syntax (CommandLineToArgvW / MSVCRT rules, also read by
 * MSYS bash): backslashes are only special in front of a double quote.
 */
export function windowsArg(value: string): string {
  if (value !== '' && !/[\s"]/.test(value)) return value
  let out = '"'
  let slashes = 0
  for (const ch of value) {
    if (ch === '\\') {
      slashes++
      continue
    }
    if (ch === '"') {
      out += '\\'.repeat(slashes * 2 + 1) + '"'
    } else {
      out += '\\'.repeat(slashes) + ch
    }
    slashes = 0
  }
  return `${out}${'\\'.repeat(slashes * 2)}"`
}

/** Executable and argument string that run `command` in the chosen shell. */
export function chainInvocation(
  command: string,
  shell: ChainShell
): { file: string; args: string } {
  if (shell.kind === 'bash') return { file: shell.path, args: `-c ${windowsArg(command)}` }
  // -EncodedCommand (UTF-16LE base64) needs no quoting; piped stdin stays available as $input.
  const encoded = Buffer.from(command, 'utf16le').toString('base64')
  return {
    file: shell.path,
    args: `-NoProfile -NonInteractive -ExecutionPolicy Bypass -EncodedCommand ${encoded}`
  }
}

/** Windows PowerShell 5.1 reads a BOM-less script in the ANSI code page; the BOM keeps UTF-8. */
const UTF8_BOM = '\uFEFF'

/**
 * Windows version of the statusline script, for Windows PowerShell 5.1 and later. Same job as
 * the POSIX one: stdin is read as UTF-8, a reading with `rate_limits` is written BOM-less to a
 * temp file and moved over `usage-raw.json`, then the original statusline gets the same input
 * and its output is copied through byte for byte. Never fails the statusline.
 */
export function windowsStatuslineScript(
  dir: string,
  originalCommand: string | null,
  shell: ChainShell
): string {
  const chain = originalCommand ? chainInvocation(originalCommand, shell) : null
  const chainLines = chain
    ? [
        'try {',
        '  $psi = New-Object System.Diagnostics.ProcessStartInfo',
        `  $psi.FileName = ${psQuote(chain.file)}`,
        `  $psi.Arguments = ${psQuote(chain.args)}`,
        '  $psi.UseShellExecute = $false',
        '  $psi.CreateNoWindow = $true',
        '  $psi.RedirectStandardInput = $true',
        '  $psi.RedirectStandardOutput = $true',
        '  $psi.RedirectStandardError = $true',
        '  $proc = [System.Diagnostics.Process]::Start($psi)',
        '  $buffer = New-Object System.IO.MemoryStream',
        '  $copy = $proc.StandardOutput.BaseStream.CopyToAsync($buffer)',
        '  $null = $proc.StandardError.ReadToEndAsync()',
        '  $bytes = $utf8.GetBytes($raw + "`n")',
        '  try { $proc.StandardInput.BaseStream.Write($bytes, 0, $bytes.Length) } catch {}',
        '  $proc.StandardInput.Close()',
        '  $copy.Wait()',
        '  $proc.WaitForExit()',
        '  $out = $buffer.ToArray()',
        '  $stdout = [Console]::OpenStandardOutput()',
        '  $stdout.Write($out, 0, $out.Length)',
        '  $stdout.Flush()',
        '} catch {}'
      ]
    : []
  return (
    UTF8_BOM +
    [
      '# Generated by ClaudeDeck. Records plan usage, then runs the original statusline.',
      "$ErrorActionPreference = 'Stop'",
      '$utf8 = New-Object System.Text.UTF8Encoding $false',
      "$raw = ''",
      'try {',
      '  $reader = New-Object System.IO.StreamReader([Console]::OpenStandardInput(), $utf8)',
      '  $raw = $reader.ReadToEnd().TrimEnd("`r", "`n")',
      '} catch {}',
      `$dir = ${psQuote(dir)}`,
      `if ($raw.Contains('"rate_limits"')) {`,
      "  $tmp = ''",
      '  try {',
      `    $file = Join-Path $dir ${psQuote(USAGE_RAW_FILE)}`,
      '    $tmp = "$file.$PID"',
      '    [System.IO.File]::WriteAllText($tmp, $raw, $utf8)',
      '    Move-Item -LiteralPath $tmp -Destination $file -Force',
      '  } catch {',
      '    if ($tmp) { try { Remove-Item -LiteralPath $tmp -Force } catch {} }',
      '  }',
      '}',
      ...chainLines,
      'exit 0',
      ''
    ].join('\n')
  )
}

/**
 * settings.json `command` for the Windows script. Claude Code runs it through Git Bash when
 * installed, else PowerShell, so the quoting must mean the same in both: forward slashes and
 * single quotes; a path with an apostrophe (PowerShell also reads the typographic ones as
 * quotes) falls back to double quotes, which both shells read literally as long as there is no
 * `$`, backtick or double quote of any kind. Null when no quoting works in both.
 * `powershell` is the absolute path from windowsPowerShellPath.
 */
export function windowsStatuslineCommand(scriptPath: string, powershell: string): string | null {
  const path = scriptPath.replace(/\\/g, '/')
  const prefix = `${powershell} -NoProfile -NonInteractive -ExecutionPolicy Bypass -File`
  if (!PS_SINGLE_QUOTE.test(path)) return `${prefix} '${path}'`
  if (/[$`]/.test(path) || PS_DOUBLE_QUOTES.test(path)) return null
  return `${prefix} "${path}"`
}
