import { existsSync, readFileSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { writeFileAtomic } from '../profile/guidelines'

export const USAGE_RAW_FILE = 'usage-raw.json'
const SCRIPT_FILE = 'statusline.sh'
const ORIGINAL_FILE = 'statusline-original.json'
const SETTINGS_MODE = 0o600
const SCRIPT_MODE = 0o755
// Any command pointing at a ClaudeDeck script is ours, even one copied from another account.
const OURS = /claudedeck\/statusline\.sh/

type Json = Record<string, unknown>

export const usageDir = (configDir: string): string => join(configDir, 'claudedeck')
export const usageRawPath = (configDir: string): string => join(usageDir(configDir), USAGE_RAW_FILE)
export const statuslineScriptPath = (configDir: string): string =>
  join(usageDir(configDir), SCRIPT_FILE)
const originalPath = (configDir: string): string => join(usageDir(configDir), ORIGINAL_FILE)
const settingsPath = (configDir: string): string => join(configDir, 'settings.json')

/** POSIX single-quote quoting; safe for any string. */
export const shQuote = (value: string): string => `'${value.replace(/'/g, `'\\''`)}'`

const isObject = (v: unknown): v is Json => !!v && typeof v === 'object' && !Array.isArray(v)

const isOurs = (statusLine: unknown): boolean =>
  isObject(statusLine) && typeof statusLine.command === 'string' && OURS.test(statusLine.command)

/**
 * Script Claude Code runs as the statusline: stores the JSON it receives (only when it carries
 * `rate_limits`) and hands the same input to the user's original statusline, if any.
 */
export function statuslineScript(dir: string, originalCommand: string | null): string {
  const chain = originalCommand
    ? `printf '%s\\n' "$input" | /bin/sh -c ${shQuote(originalCommand)} 2>/dev/null`
    : ':'
  return [
    '#!/bin/sh',
    '# Generated by ClaudeDeck. Records plan usage, then runs the original statusline.',
    'input=$(cat 2>/dev/null)',
    `dir=${shQuote(dir)}`,
    'case $input in',
    `  *'"rate_limits"'*)`,
    `    tmp="$dir/${USAGE_RAW_FILE}.$$"`,
    `    { printf '%s' "$input" > "$tmp" && mv -f "$tmp" "$dir/${USAGE_RAW_FILE}"; } 2>/dev/null ||`,
    `      rm -f "$tmp" 2>/dev/null`,
    '    ;;',
    'esac',
    chain,
    'exit 0',
    ''
  ].join('\n')
}

/** Parsed settings.json; {} when missing or empty, null when it is not a JSON object. */
function readSettings(file: string): Json | null {
  if (!existsSync(file)) return {}
  const text = readFileSync(file, 'utf8')
  if (text.trim() === '') return {}
  try {
    const json: unknown = JSON.parse(text)
    return isObject(json) ? json : null
  } catch {
    return null
  }
}

function readOriginal(configDir: string): Json | null {
  try {
    const json: unknown = JSON.parse(readFileSync(originalPath(configDir), 'utf8'))
    return isObject(json) ? json : null
  } catch {
    return null
  }
}

const commandOf = (statusLine: Json | null): string | null =>
  statusLine && typeof statusLine.command === 'string' && statusLine.command.trim() !== ''
    ? statusLine.command
    : null

const writeIfChanged = (file: string, content: string, mode: number): boolean => {
  if (existsSync(file) && readFileSync(file, 'utf8') === content) return false
  writeFileAtomic(file, content, mode)
  return true
}

/**
 * Points the account's statusline at ClaudeDeck's script, keeping any statusline the account
 * already had as the chained original. Only the `statusLine` key is touched. Returns true when
 * anything changed; leaves invalid settings.json alone (returns false).
 */
export function installStatusline(
  configDir: string,
  scriptPath: string = statuslineScriptPath(configDir)
): boolean {
  const file = settingsPath(configDir)
  const settings = readSettings(file)
  if (!settings) {
    console.warn('[usage] settings.json is not valid JSON; statusline not installed')
    return false
  }

  let changed = false
  const current = settings.statusLine
  let original: Json | null = null
  if (isOurs(current)) {
    original = readOriginal(configDir)
  } else if (isObject(current)) {
    // A statusline that is not ours is the user's latest one; it becomes the chained original.
    original = current
    changed = writeIfChanged(originalPath(configDir), JSON.stringify(current, null, 2), 0o600)
  } else if (existsSync(originalPath(configDir))) {
    // No usable statusline left, so a previously saved original is stale.
    rmSync(originalPath(configDir), { force: true })
    changed = true
  }

  const script = statuslineScript(usageDir(configDir), commandOf(original))
  changed = writeIfChanged(scriptPath, script, SCRIPT_MODE) || changed

  const extras = isObject(original) ? { ...original } : {}
  delete extras.type
  delete extras.command
  const entry = { ...extras, type: 'command', command: shQuote(scriptPath) }
  if (JSON.stringify(current) !== JSON.stringify(entry)) {
    writeFileAtomic(
      file,
      JSON.stringify({ ...settings, statusLine: entry }, null, 2),
      SETTINGS_MODE
    )
    changed = true
  }
  return changed
}

/** Restores the original statusline (or removes ours) and deletes ClaudeDeck's script files. */
export function uninstallStatusline(configDir: string): boolean {
  const file = settingsPath(configDir)
  const settings = readSettings(file)
  let changed = false
  if (settings && isOurs(settings.statusLine)) {
    const original = readOriginal(configDir)
    const next = { ...settings }
    if (original) next.statusLine = original
    else delete next.statusLine
    writeFileAtomic(file, JSON.stringify(next, null, 2), SETTINGS_MODE)
    changed = true
  }
  for (const path of [statuslineScriptPath(configDir), originalPath(configDir)]) {
    if (existsSync(path)) {
      rmSync(path, { force: true })
      changed = true
    }
  }
  return changed
}
